### ISSUE TITLE
in QtMeatObjectEx: the setProperty always return false

### ISSUE THREAD

**Issue by liumeng009** [touwoyimuli/QtExamples#10]
![image](https://user-images.githubusercontent.com/24890055/164202691-abce4873-c5d9-4a3f-813b-b54a108bd7f5.png)

it seems the setProperty do not work

**Comment by liumeng009** [comment]
m_girl->setProperty("sex", "Gril");         //动态属性
this line add a sex property, but onclassInfo do not print it

**Comment by XMuli** [comment]
“sex” 的属性是可以被打印出来的（点击 age 增加 Btn 或者 spinbox）
![image](https://user-images.githubusercontent.com/33887845/164277846-1df7a69a-4bd2-4327-a11d-558b96945604.png)

运行·如图
![image](https://user-images.githubusercontent.com/33887845/164278493-2016be9c-889b-41d7-813c-17c55d060d34.png)



而你说说，没有被打印出来原因是 动态属性没有被 `QObject::property() ` 给显示出来 

> QObject::setProperty() 函数可以在运行时为类定义一个新的属性，称之为**动态属性**。动态属性是针对类的实例定义的。

![image](https://user-images.githubusercontent.com/33887845/164276296-660f8e1f-8891-4ec0-b9dc-15ad4cbe0c85.png)

**Comment by liumeng009** [comment]
谢谢 了解了
QMetaObject是编译器由MOC生成的，所以**QMetaObject无法知道动态属性**
它是该类所有对象共享的，也就是一样的。
而动态属性是放入父类对象QObject中的
![image](https://user-images.githubusercontent.com/24890055/164363113-1d1e33ec-f40d-433a-84f9-7be393552640.png)
必须使用父类提供的property("sex")进行访问。
