### ISSUE TITLE
第三部分里的第一条和最后一条都没有超链接吗？

### ISSUE THREAD

**Issue by ice909** [touwoyimuli/QtExamples#11]
RT

**Comment by XMuli** [comment]
> 一个默认的Qt Widget项目 【空】

优先级较低，属基础，且实际内容有被包含于第一部分中。


> Qt 修改 *.svg 文件的颜色【ExChangeSVGColor】

嗯，且预估笔墨不多， `ExChangeSVGColor`  中的代码亦即是注释/文档
