### ISSUE TITLE
可以一直到 FreeBSD 么？

### ISSUE THREAD

**Issue by osenberg-x** [touwoyimuli/QtExamples#6]
大佬，从底层上来讲，移植到 FreeBSD 困难大么？

**Comment by XMuli** [comment]
what ? 应该是可以直接在上面跑的~

还是说你回复错了地方？

**Comment by osenberg-x** [comment]
没有回复错，我就是想提前问一下，想在 FreeBSD 上用，因为看文档上只有 Windows，Macos，Linux 的支持

**Comment by XMuli** [comment]
可以
